# Generated by Django 5.2.7 on 2025-10-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerecord',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
